---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check that a page returns a status 200 and fail if the string 'Dive Into Ansible' is not in the page contents
    uri:
      url: http://localhost
      return_content: yes
    register: this
    failed_when: "'Dive Into Ansible' not in this.content"
